name: Build and Deploy Next.js via FTP

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone https://gitea.ranggamaulana.xyz/ranggamaulanaxyz/fourflazz-admin-app.git .
          git checkout main

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: |
          npm run build
          npx next export

      - name: Install lftp
        run: |
          apt-get update
          apt-get install -y lftp

      - name: Deploy via FTP
        run: |
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" $FTP_SERVER <<EOF
          mirror -R ./out /public_html/ --delete --verbose
          quit
          EOF
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}